export default {
  DASHBOARD: '/dashboard',
  LOGIN: '/login',
  PASSWORD_RECOVERY_REQUEST: '/password-recovery/request',
  PASSWORD_RECOVERY_VERIFICATION: '/password-recovery/verification',
  INVITATION_VERIFICATION: '/invitation/verification',
  SITES: '/sites',
  SITES_USERS: '/sites/users',
  SITES_USERS_ID: '/sites/users/:id',
  SITES_DEVICES: '/sites/devices',
  SITES_DEVICES_ID: '/sites/devices/:id',
  ACCESS_CONTROLS: '/access-controls',
  ACCESS_CONTROLS_KEYS: '/access-controls/keys',
  ACCESS_CONTROLS_LEVELS: '/access-controls/levels',
  ACCESS_CONTROLS_EVENTS: '/access-controls/events',
  SETTINGS: '/settings',
  SETTINGS_ADMINISTRATORS: '/settings/administrators',
  SETTINGS_ROLES: '/settings/roles',

  API: {
    LOGIN: 'auth/login/admin',
    REFRESH_TOKEN: 'auth/refresh-token',
    PASSWORD_RECOVERY_REQUEST: 'auth/forgot-password',
    PASSWORD_RECOVERY_VERIFICATION: 'auth/reset-password',
    USERS: 'users',
    USERS_ID: 'users/:id',
    USERS_ID_DEVICES: 'users/:id/devices',
    USERS_ID_CHANGE_IMAGE: 'users/:id/change-image',
    USERS_INVITE: 'users/invite',
    USERS_INVITE_RESEND: 'users/invite/resend',
    USERS_ACCEPT_INVITE: 'auth/invite-accept',
    SITES: 'sites',
    SITES_OVERVIEW: 'sites/overview',
    SITES_ID: 'sites/:id',
    SITES_ID_SELECT: 'auth/sites/:id',
    SITES_ID_CHANGE_IMAGE: 'sites/:id/change-image',
    ACCESS_KEYS: 'access-keys',
    ACCESS_KEYS_OVERVIEW: 'access-keys/overview',
    ACCESS_KEYS_ID: 'access-keys/:id',
    ACCESS_KEYS_ID_ATTACH: 'access-keys/:id/attach',
    ACCESS_KEYS_ID_DETACH: 'access-keys/:id/detach',
    ACCESS_KEYS_ID_TIME_SCHEDULE: 'access-keys/:id/time-schedule',
    ACCESS_KEYS_ID_TIME_SCHEDULE_ID_ACCESS_TIMES_ID:
      'access-keys/:id/time-schedule/:timeScheduleId/access-times/:accessTimeId',
    ACCESS_LEVELS: 'access-groups',
    ACCESS_LEVELS_ID: 'access-groups/:id',
    ACCESS_LEVELS_ID_ATTACH: 'access-groups/:id/attach',
    ACCESS_LEVELS_ID_DETACH: 'access-groups/:id/detach',
    ACCESS_LEVELS_ID_USERS: 'access-groups/:id/users',
    ACCESS_LEVELS_ID_DEVICES: 'access-groups/:id/devices',
    ACCESS_LEVELS_ID_TIME_SCHEDULE: 'access-groups/:id/time-schedule',
    ACCESS_LEVELS_ID_TIME_SCHEDULE_ID_ACCESS_TIMES_ID:
      'access-groups/:id/time-schedule/:timeScheduleId/access-times/:accessTimeId',
    ACCESS_LEVELS_ID_EXCEPTIONS: 'access-groups/:id/exceptions',
    ACCESS_LEVELS_ID_EXCEPTIONS_ID: 'access-groups/:id/exceptions/:exceptionId',
    DEVICES: 'devices',
    DEVICES_OVERVIEW: 'devices/overview',
    DEVICES_ID: 'devices/:id',
    DEVICES_ID_USERS: 'devices/:id/users',
    DEVICES_ID_USERS_ID_CHANGE_VISIBILITY:
      'devices/:id/users/:userId/change-visibility',
    DEVICES_ID_USERS_ID_ADD: 'devices/:id/users/:userId/add',
    DEVICES_ID_USERS_ID_REMOVE: 'devices/:id/users/:userId/remove',
    DEVICES_ID_CONFIGURATION: 'devices/:id/configuration',
    DEVICES_ID_RESET: 'devices/:id/reset',
    DEVICES_ID_CHANGE_IMAGE: 'devices/:id/change-image',
    DEVICES_REGISTRATION: 'devices/registration',
    DEVICES_ID_ACTIVATE: 'auth/devices/:id/activate',
    DEVICES_ID_CHANGE_PASSWORD: 'auth/devices/:id/change-password',
    DEVICE_REGISTRATION_VERIFICATION: 'auth/device-registration-verification',
    PERMISSIONS: 'permissions',
    ROLES: 'roles',
    ROLES_ID: 'roles/:id',
    STATISTICS: 'statistics',
    COUNTRIES: 'countries',
    VERSIONS: 'versions',
    MQTT_EVENT_HANDLER: 'mqtt/event-handler',
  },

  build: (path: string, ...params: string[]): string =>
    path.replace(/(:\w+)/g, () => params.shift() || ''),
};
